
name: SQL Injection Testing

on:
  push:
    branches:
      - dev
      - master  # Change to your default branch name if needed

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v2



      - name: Download and Extract SQLMap
        run: |
          wget https://github.com/sqlmapproject/sqlmap/archive/master.zip
          unzip master.zip
          cd sqlmap-master
          ls  # List the contents of the directory to verify sqlmap.py is present



      - name: Check Directory Contents
        run: |
          ls -R  # List all files and directories recursively for debugging

      - name: SQL Injection Testing
        run: |
          cd sqlmap-master
          python sqlmap.py -u https://github.com/Ragavendira1/aidevsecopsdemo/src/main/resources -p vulnerable-param --batch --level 5 --risk 3
          





