name: SonarQube Scan

on:
  push:
    branches:
      - dev
      - master

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SonarCloud Quality Gate Status
        run: |
            sonar_project_key='Ragavendira1_aidevsecopsdemo'
            sonar_quality_gate_status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=${sonar_project_key}")
              pass_percentage_threshold=100  # Define your desired threshold here

            if [[ $(echo "$sonar_quality_gate_status" | jq -r '.projectStatus.status') == "OK" ]]; then
            echo "Quality Gate Status: passed"
            else
              echo "Quality Gate Status: failed"
              exit 1
            fi
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}